#!/bin/sh

rm -r dist
mkdir dist

submodules=("assignments" "discussions" "homepage" "modules" "pages" "task_bar" )

for m in "${submodules[@]}"; do
    cd $m

    rm -r out dist &> /dev/null
    mkdir out dist

    tsc --pretty --strict --removeComments
    esbuild --bundle out/index.js --outfile=dist/user.js --banner:js="$(cat info.txt)"

    cp dist/user.js ../dist/$m.js
    rm -r out dist &> /dev/null

    cd ..
done
