#!/bin/sh

rm -r dist
mkdir dist

#submodules=("discussions" "gradebook" "modules" "pages" "taskbar")
submodules=("discussions" "pages")

for m in "${submodules[@]}"; do
    cd $m

    chmod +x build
    ./build && cp dist/user.js ../dist/$m.js

    rm -r dist
    cd ..
done
